/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account-email` | `/create-account-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account-password` | `/create-account-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account` | `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/story/read/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-account-email` | `/create-account-email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-account-password` | `/create-account-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create-account` | `/create-account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/story/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/story/read/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-account-email${`?${string}` | `#${string}` | ''}` | `/create-account-email${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-account-password${`?${string}` | `#${string}` | ''}` | `/create-account-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create-account${`?${string}` | `#${string}` | ''}` | `/create-account${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/downloads${`?${string}` | `#${string}` | ''}` | `/downloads${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account-email` | `/create-account-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account-password` | `/create-account-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create-account` | `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/story/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/story/read/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/story/read/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
